apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/name: matchmaker
  creationTimestamp: "2024-01-16T20:14:50Z"
  labels:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: matchmaker
  name: matchmaker-sa
  namespace: opr-develop
  resourceVersion: "130593944"
  uid: 6c84d303-afb2-4725-a07e-c2f4ab04a1f5
