apiVersion: v2
name: eck-operator
icon: https://helm.elastic.co/icons/eck.png
description: Elastic Cloud on Kubernetes (ECK) operator
home: https://github.com/elastic/cloud-on-k8s
type: application
version: 2.16.1-bb.0
appVersion: 2.16.1
kubeVersion: ">=1.21.0-0"
keywords:
  - Logstash
  - Elasticsearch
  - Kibana
  - APM Server
  - Beats
  - Enterprise Search
  - Elastic Stack
  - Operator
maintainers:
  - name: Elastic
    email: eck@elastic.co
dependencies:
  - name: eck-operator-crds
    version: 2.16.1
    condition: installCRDs
    repository: "file://charts/eck-operator-crds"
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/applicationVersions: |
    - ECK Operator: 2.16.1
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find upstream chart's release notes and CHANGELOG here](https://github.com/elastic/cloud-on-k8s/releases)
    - [Find upstream application's release notes and CHANGELOG here](https://www.elastic.co/guide/en/cloud-on-k8s/current/eck-release-notes.html)
  helm.sh/images: |
    - name: eck-operator
      image: registry1.dso.mil/ironbank/elastic/eck-operator/eck-operator:2.16.1
