{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-elasticsearch-allow
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: elastic-operator
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          common.k8s.elastic.co/type: elasticsearch
    ports:
    - port: 9200
      protocol: TCP
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-kibana-allow
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: elastic-operator
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          common.k8s.elastic.co/type: kibana
    ports:
    - port: 5601
      protocol: TCP
  policyTypes:
  - Egress
{{- end }}
