apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-elasticsearch-data-elasticsearch-es-default-0  # Ensure unique PV name
  annotations:
    pv.kubernetes.io/migrated-to: ebs.csi.aws.com
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  finalizers:
    - external-provisioner.volume.kubernetes.io/finalizer
    - kubernetes.io/pv-protection
    - external-attacher/ebs-csi-aws-com
  labels:
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1b
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0dea34882b4db9dd1  # ✅ Ensure this volume ID exists
  capacity:
    storage: 10Gi  # ✅ Ensure PVC matches this value
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-data-elasticsearch-es-default-0
    namespace: opr-develop
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - us-east-1b
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - us-east-1
  persistentVolumeReclaimPolicy: Retain  # ✅ Change to "Delete" if you want automatic deletion
  storageClassName: gp2
  volumeMode: Filesystem
status:
  phase: Available
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     pv.kubernetes.io/bind-completed: "yes"
#     pv.kubernetes.io/bound-by-controller: "yes"
#     volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
#     volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
#   finalizers:
#     - kubernetes.io/pvc-protection
#   labels:
#     app.kubernetes.io/instance: opr
#     app.kubernetes.io/name: elasticsearch  # ✅ Updated from "rabbitmq"
#   name: elasticsearch-data-elasticsearch-es-default-0
#   namespace: opr-develop
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi  # ✅ Ensure this matches PV capacity
#   storageClassName: gp2
#   volumeMode: Filesystem
# status:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 10Gi  # ✅ Match this with PV
#   phase: Bound
