apiVersion: v1
data:
  REFLECTMULTIPLAYER_ConnectionStrings__MatchmakerDatabase: SG9zdD1vcHItcG9zdGdyZXNxbDtEYXRhYmFzZT1NYXRjaG1ha2VyO1VzZXJuYW1lPW1hdGNobWFrZXJfc2VydmljZTtQYXNzd29yZD1yZWZsZWN0
  REFLECTMULTIPLAYER_Mumble__RestApiPassword: bXVybXVyLXJlc3Qtc2VjcmV0LWtleQ==
  REFLECTMULTIPLAYER_Mumble__RestApiUsername: cmVmbGVjdA==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: opr
    meta.helm.sh/release-namespace: opr-develop
  creationTimestamp: "2024-01-16T20:14:52Z"
  labels:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matchmaker
    helm.sh/chart: reflect-common-chart-1.0.0
  name: matchmaker-secrets
  namespace: opr-develop
  resourceVersion: "170870273"
  uid: a4147233-b14e-4b70-b429-d7a45f1190be
type: Opaque
