apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: opr
    meta.helm.sh/release-namespace: opr-develop
  creationTimestamp: "2024-01-16T20:14:50Z"
  labels:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matchmaker
    helm.sh/chart: reflect-common-chart-1.0.0
  name: matchmaker-sa
  namespace: opr-develop
  resourceVersion: "130593944"
  uid: 6c84d303-afb2-4725-a07e-c2f4ab04a1f5
