apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: opr
    meta.helm.sh/release-namespace: opr-develop
  creationTimestamp: "2024-01-16T20:15:02Z"
  labels:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matchmaker
    helm.sh/chart: reflect-common-chart-1.0.0
  name: matchmaker
  namespace: opr-develop
  resourceVersion: "191643267"
  uid: f70f9130-8c8c-43d5-b37c-49e1bd5c15ac
spec:
  clusterIP: 10.43.54.123
  clusterIPs:
  - 10.43.54.123
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: prom-publisher
    port: 1234
    protocol: TCP
    targetPort: 1234
  - name: grpc
    port: 10042
    protocol: TCP
    targetPort: 10042
  selector:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/name: matchmaker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
