apiVersion: v1
data:
  job.yml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: netcode-job-{{ Ident }}
      namespace: {{ Namespace }}
    spec:
      template:
        metadata:
          labels:
            app: netcode-job-{{ Ident }}
        spec:
          restartPolicy: Never
          nodeSelector:
            {{ NodeSelector }}
          serviceAccountName: netcode-sa
          volumes:
          - name: netcode-config
            emptyDir: {}
          initContainers:
            - name: netcode-init
              image: {{ InitImage }}
              imagePullPolicy: "Always"
              volumeMounts:
              - name: netcode-config
                mountPath: /etc/reflect
              env:
                  - name: REFLECT_NETCODE_NODE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
                  - name: CERTS_SECRET_NAME
                    value: {{ CertsSecretName }}
                  - name: REFLECT_SENTRY_DSN
                    value: {{ SentryDSN }}
                  - name: NAMESPACE
                    value: {{ Namespace }}
          imagePullSecrets:
            - name: regcred-gcp
          containers:
            - name: netcode-server
              image: {{ NetcodeImage }}
              imagePullPolicy: "Always"
              ports:
                - containerPort: 30303
                  name: mlapi
                  protocol: UDP
              env:
                  - name: REFLECT_NETCODE_NODE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
                  - name: REFLECT_NETCODE_POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: MATCHMAKER_ENABLE
                    value: "true"
                  - name: MATCHMAKER_HOST
                    value: {{ MatchMakerEndpoint }}
                  - name: MATCHMAKER_PORT
                    value: "10042"
                  - name: REFLECT_NETCODE_IP
                    value: {{ NetcodeServerAddress }}
                  - name: REFLECT_SENTRY_DSN
                    value: {{ SentryDSN }}
              volumeMounts:
              - name: netcode-config
                mountPath: /etc/reflect
              resources:
                requests:
                  memory: "400Mi"
                  cpu: "2000m"
                limits:
                  memory: "800Mi"
                  cpu: "2000m"
  service.yml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: netcode-svc-{{ Ident }}
      namespace: {{ Namespace }}
      labels:
        app: netcode-svc-{{ Ident }}
        reflectComponent: netcode
    spec:
      type: NodePort
      selector:
        app: netcode-job-{{ Ident }}
      ports:
        - port: 30303
          targetPort: mlapi
          name: mlapi
          protocol: UDP
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: opr
    meta.helm.sh/release-namespace: opr-develop
  creationTimestamp: "2024-01-15T18:42:03Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: netcode-manifests
  namespace: opr-develop
  resourceVersion: "149706419"
  uid: 077fdaa9-3f87-4f55-a7f7-8b630ddffce0
