apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: opr
    meta.helm.sh/release-namespace: opr-develop
  creationTimestamp: "2024-01-16T20:14:51Z"
  labels:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opr-reflect-common-chart
    helm.sh/chart: reflect-common-chart-1.0.0
  name: netcode-sa
  namespace: opr-develop
  resourceVersion: "130593948"
  uid: 0abade40-27e0-466b-b574-3f8f01b77e1b
