apiVersion: v1
data:
  REFLECT_COMPONENT: murmur
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: opr
    meta.helm.sh/release-namespace: opr-develop
  creationTimestamp: '2024-04-03T22:26:01Z'
  labels:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: murmur
    helm.sh/chart: reflect-common-chart-2.0.5
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:REFLECT_COMPONENT: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
      manager: helm
      operation: Update
      time: '2024-04-04T20:19:05Z'
  name: murmur-config
  namespace: opr-develop
  resourceVersion: '199680589'
  uid: cfb5668d-e56e-4bec-9e3a-0cada8d269f0
