apiVersion: v1
data:
  APP_SECRET_KEY: c3VwZXJzZWNyZXQ=
  ICE_SECRET: bXVybXVyLWljZS1zZWNyZXQta2V5
  USERS: cmVmbGVjdDptdXJtdXItcmVzdC1zZWNyZXQta2V5
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: opr
    meta.helm.sh/release-namespace: opr-develop
  creationTimestamp: '2024-04-03T22:25:56Z'
  labels:
    app.kubernetes.io/instance: opr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mumble-rest
    helm.sh/chart: reflect-common-chart-2.0.5
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:APP_SECRET_KEY: {}
          f:ICE_SECRET: {}
          f:USERS: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
        f:type: {}
      manager: helm
      operation: Update
      time: '2024-04-04T20:19:01Z'
  name: mumble-rest-secrets
  namespace: opr-develop
  resourceVersion: '199680548'
  uid: df8a6e50-8470-4628-9ed2-b3b0fbff4ab8
